redis:
  url: 127.0.0.1:6379
  password:
  key: free_proxy_pool:v1

service:
  url: 127.0.0.1:5555

# 代理地址
martian: 127.0.0.1:10888
# 使用代理池代理的模式 random 或者 max
martian_mode: max

# 代理池中最大存在的代理数
pool_cap: 200
# 测试周期
test_time: "*/1 * * * *"
# 抓取周期
crawler_time: "*/5 * * * *"
# 测试链接
test_urls:
  - https://ada.baidu.com
# 新鲜度分数
flash_score: 5
